### ISSUE TITLE
H3D 数据集下载失败

### ISSUE THREAD

**Issue by shuyuanwen** [YuheD/MAPS#1]
H3D 数据集下载失败

dataset数据集文件中，源地址失效，无法下载
https://cloud.tsinghua.edu.cn/f/d4e612e44dc04d8eb01f/?dl=1

**Comment by YuheD** [comment]
你好，

这个数据集不是我们发布的，您可以向原作者咨询一下现在的下载方式。
(Hand-3D-Studio:A New Multi-View System For 3D Hand Reconstruction)[https://www.yangangwang.com/papers/icassp2020-hand3dstudio/ZHAO-H3S-2020-02.html]
